export const environment = {
  production: true,
  USERSERVICE_USER: 'https://backend.20.190.17.22.nip.io/api/User',
  USERSERVICE_REPORT: 'https://backend.20.190.17.22.nip.io/api/Report',
  MUSICSERVICE_UPLOADMUSIC: 'https://backend.20.190.17.22.nip.io/api/UploadMusic',
  MUSICSERVICE_PLAYLIST: 'https://backend.20.190.17.22.nip.io/api/Playlist',
  MUSICSERVICE_MUSICPLAYLIST: 'https://backend.20.190.17.22.nip.io/api/MusicPlaylist',
  MUSICSERVICE_COMMENTS: 'https://backend.20.190.17.22.nip.io/api/Comments',
  PROJECTSERVICE_USERPROJECT: 'https://backend.20.190.17.22.nip.io.net/api/UserProject',
  PROJECTSERVICE_SAVEDPROJECT: 'https://backend.20.190.17.22.nip.io.net/api/SavedProject',
  PROJECTSERVICE_TRACK: 'https://backend.20.190.17.22.nip.io.net/api/Track',
  PROJECTSERVICE_PATTERN: 'https://backend.20.190.17.22.nip.io.net/api/Pattern',
  PROJECTSERVICE_SAMPLE: 'https://backend.20.190.17.22.nip.io.net/api/Sample',
  PROJECTSERVICE_SAMPLEPLAYLIST: 'https://backend.20.190.17.22.nip.io.net/api/SamplePlaylist',
  PROJECTSERVICE_SAMPLESETS: 'https://backend.20.190.17.22.nip.io.net/api/SampleSets',
  PROJECTSERVICE_USERSSAMPLE: 'https://backend.20.190.17.22.nip.io.net/api/UsersSample',
  PROJECTSERVICE_USERSSAMPLESETS: 'https://backend.20.190.17.22.nip.io.net/api/UsersSampleSets',
  PROJECTSERVICE_SAMPLESBLOBUPLOAD: 'https://backend.20.190.17.22.nip.io.net/api/SampleBlob',
  PROJECTSERVICE_MUSICBLOBUPLOAD: 'https://backend.20.190.17.22.nip.io/api/UploadMusicBlob',

  SAMPLE_STORAGE: 'https://revmixerstoragep3.blob.core.windows.net/uploadsample',
  MUSIC_STORAGE: 'https://revmixerstoragep3.blob.core.windows.net/uploadmusic',

  DOMAIN: 'revmixer.us.auth0.com',
  CLIENT_ID: 'dkWA6cBjs14xdCEU4vWe3tsH7vRNWwra',
};
