# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# - script: |
#     npm install -g @angular/cli
#     npm install
#     ng build --prod
#   displayName: 'npm install and build'

- task: Docker@2
  inputs:
    containerRegistry: 'wysparDockerHub'
    repository: 'revmixerfrontend'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '**'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(583825bd-d55a-497c-bfe6-2e3972e128e2)'
    appType: 'webAppContainer'
    WebAppName: 'revmix'
    DockerNamespace: 'wyspar123'
    DockerRepository: 'revmixerfrontend'
    DockerImageTag: 'latest'