apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  # namespace: ingress-basic
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api/$1/$2$3
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: project-service
          servicePort: 80
        path: /api/(UserProject|SavedProject|Track|Pattern|Sample)(/|$)(.*)
      - backend:
          serviceName: music-service
          servicePort: 80
        path: /api/(UploadMusic|Playlist|MusicPlaylist|Comments)(/|$)(.*)
      - backend:
          serviceName: user-service
          servicePort: 80
        path: /api/(User|Report)(/|$)(.*)
      # - backend:
      #     serviceName: project-service
      #     servicePort: 80
      #   path: /(.*)
