apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  # namespace: ingress-basic
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2$3$4
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
      - frontend.20.190.17.22.nip.io
      - backend.20.190.17.22.nip.io
      secretName: app-web-cert
  rules:
  - host: backend.20.190.17.22.nip.io
    http:
      paths:
      - backend:
          serviceName: project-service
          servicePort: 80
        path: /(api/)(UserProject|SavedProject|Track|Pattern|Sample|SamplePlaylist|SampleSets|UsersSample|UsersSampleSets|SampleBlob|UploadMusicBlob)(/|$)(.*)
      - backend:
          serviceName: music-service
          servicePort: 80
        path: /(api/)(UploadMusic|Playlist|MusicPlaylist|Comments)(/|$)(.*)
      - backend:
          serviceName: user-service
          servicePort: 80
        path: /(api/)(User|Report)(/|$)(.*)
      # - backend:
      #     serviceName: project-service
      #     servicePort: 80
      #   path: /(.*)
  - host: frontend.20.190.17.22.nip.io
    http:
      paths:
      - backend:
          serviceName: angular
          servicePort: 80
        path: /(.*)
